#ifndef SEEDTOOL_LOGO_H_
#define SEEDTOOL_LOGO_H_

#include <stdint.h>

/* The splash artwork: sixteen colours at two pixels per byte, high nibble
 * first, with a palette of RGB565 entries. Generated by tools/make_logo.py from
 * assets/logo.png; the width is even so every row starts on a byte boundary.
 *
 * This is the only picture in the firmware. It is drawn by indexing a palette
 * from a flat array, not by linking a graphics library: the audit exists to
 * prove there is no generic graphics surface, and a logo must not become one. */
#define SEEDTOOL_LOGO_WIDTH 98
#define SEEDTOOL_LOGO_HEIGHT 110
#define SEEDTOOL_LOGO_COLOURS 16
#define SEEDTOOL_LOGO_BYTES (SEEDTOOL_LOGO_WIDTH * SEEDTOOL_LOGO_HEIGHT / 2)

extern const uint16_t seedtool_logo_palette[SEEDTOOL_LOGO_COLOURS];
extern const uint8_t seedtool_logo_pixels[SEEDTOOL_LOGO_BYTES];

#endif
