#!/usr/bin/env python3
"""Convert the Origo logo artwork into the C array the firmware draws.

Authoring tool, run by hand when the artwork changes; the generated C file is
committed and is what builds. Pillow is needed here and only here: the firmware,
`origo_verify.py` and the tests stay dependency-free.

The whole logo is used, wordmark and tagline included, so the opening screen
shows the mark as it was drawn rather than a reassembly of it. That is also how
Jade's splash works, and it is why the artwork is cropped to its ink rather than
to the tree alone.

    python3 tools/make_logo.py assets/logo.png main/seedtool_logo.c
"""

import argparse
from pathlib import Path
import sys

try:
    from PIL import Image
except ImportError:  # pragma: no cover - authoring-only dependency
    sys.exit("this tool needs Pillow: pip install pillow")


WIDTH = 98
HEIGHT = 110
COLOURS = 16
# Anything brighter than this on any channel is artwork rather than background.
INK_LEVEL = 45


def rgb565(colour):
    red, green, blue = colour
    return ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)


def artwork_box(image):
    """The bounding box of everything drawn, background excluded."""
    pixels = image.load()
    width, height = image.size
    rows = [
        sum(1 for x in range(width) if max(pixels[x, y]) > INK_LEVEL)
        for y in range(height)
    ]
    inked = [y for y, count in enumerate(rows) if count > 2]
    if not inked:
        raise SystemExit("no artwork found")
    top, bottom = inked[0], inked[-1]
    columns = [
        x
        for x in range(width)
        if any(max(pixels[x, y]) > INK_LEVEL for y in range(top, bottom + 1))
    ]
    return columns[0], top, columns[-1] + 1, bottom + 1


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    image = Image.open(args.source).convert("RGB")
    tree = image.crop(artwork_box(image)).resize((WIDTH, HEIGHT), Image.LANCZOS)

    # The artwork's background is a noisy near-black. Left alone it eats most of
    # the palette on shades nobody can tell apart, so it is flattened to one
    # black first and the sixteen slots go to the tree.
    flattened = tree.load()
    for y in range(HEIGHT):
        for x in range(WIDTH):
            if max(flattened[x, y]) <= INK_LEVEL:
                flattened[x, y] = (0, 0, 0)
    quantised = tree.quantize(colors=COLOURS, method=Image.MEDIANCUT, dither=Image.NONE)

    palette = quantised.getpalette()[: COLOURS * 3]
    entries = [rgb565(tuple(palette[i * 3 : i * 3 + 3])) for i in range(COLOURS)]
    indices = list(quantised.tobytes())
    if len(indices) != WIDTH * HEIGHT or max(indices) >= COLOURS:
        raise SystemExit("quantisation produced an out-of-range index")

    # Two pixels per byte, high nibble first. The width is even so no row is
    # padded and a row start is always a byte boundary.
    packed = bytearray()
    for i in range(0, len(indices), 2):
        packed.append((indices[i] << 4) | indices[i + 1])

    lines = [
        "/* Generated by tools/make_logo.py from assets/logo.png. Do not edit. */",
        "",
        '#include "seedtool_logo.h"',
        "",
        f"const uint16_t seedtool_logo_palette[SEEDTOOL_LOGO_COLOURS] = {{",
    ]
    lines += [
        "    " + " ".join(f"0x{v:04x}," for v in entries[i : i + 8])
        for i in range(0, COLOURS, 8)
    ]
    lines += ["};", "", "const uint8_t seedtool_logo_pixels[SEEDTOOL_LOGO_BYTES] = {"]
    lines += [
        "    " + " ".join(f"0x{b:02x}," for b in packed[i : i + 12])
        for i in range(0, len(packed), 12)
    ]
    lines += ["};", ""]
    args.output.write_text("\n".join(lines))
    print(f"{args.output}: {WIDTH}x{HEIGHT}, {COLOURS} colours, "
          f"{len(packed)} pixel bytes + {COLOURS * 2} palette bytes")


if __name__ == "__main__":
    main()
